services:
    web:
        build: .
        ports:
            - "8000:8000"
            - "5173:5173"
        depends_on:
            - db
    db:
        image: postgres:17
        shm_size: 128mb
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
